version: "3.9"

services:
  flask:
    image: antalvarenga/poetry-flask:latest
    expose:
      - 8000
    networks:
      - internal
  nginx:
    image: nginx:latest
    ports:
      - 1337:80
      # - 443:443
    networks:
      - internal
    volumes:
      - ./config/nginx_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask


networks:
  internal:
