version: "3.9"

services:
  flask:
    image: antalvarenga/poetry-flask:latest
    expose:
      - 5000
    networks:
      - internal
  nginx:
    image: antalvarenga/nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
    restart: always
    depends_on:
      - flask
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw


networks:
  internal:
