version: "3.9"

services:
  flask:
    image: antalvarenga/poetry-flask:latest
    expose:
      - 5000
    networks:
      - internal
  nginx:
    image: antalvarenga/nginx:latest
    ports:
      - 1337:80
      # - 443:443
    networks:
      - internal
    depends_on:
      - flask


networks:
  internal:
