services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5010:5010
    environment:
      # hide in a real application as env var
      - SQLALCHEMY_DATABASE_URI=postgresql://flask_app_root:123456@database:5432/flask_app
    networks:
      - default
    depends_on:
      - database
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    # restart: always
    networks:
      - default
    depends_on:
      - flask
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  database:
    image: postgres:17
    # restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - database_vol:/var/lib/postgresql/data
    networks:
      - default
    environment:
      # hide this in a real application as env vars
      - POSTGRES_USER=flask_app_root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=flask_app
volumes:
  database_vol:
networks:
  default:
