version: "3.9"

services:
  flask:
    image: antalvarenga/poetry-flask:latest
    expose:
      - 5000
  nginx:
    image: antalvarenga/nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    # restart: always
    depends_on:
      - flask
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  database:
    image: bitnami/postgresql:13-debian-11
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - database_vol:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=flask_app
      - POSTGRESQL_USERNAME=flask_app_root
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_POSTGRES_PASSWORD=123456
volumes:
  database_vol:
